development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: timekeep_development

test:
  adapter: test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: timekeep_production
